title: Linked Timestamp WordPress Plugin
description: Add a link to timestamps on your WordPress powered website. 
#show_downloads: false
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one